configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mpesaflow-evansso%2Fmpesaflow-e2ef20ec2d49733ebdaa0d223073da819f21b7123d31606e61c5d2c449c59e1d.yml
