configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mpesaflow-evansso%2Fmpesaflow-956082958e0e720b93b112e38faa1c493f3c5a17e74da1e629d7c8c402c5230f.yml
